CREATE DATABASE ALMACEN;

USE ALMACEN;

CREATE TABLE ROL (
    ID_ROL INT(2) AUTO_INCREMENT NOT NULL,
    TIPO VARCHAR(20),
    PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIOS (
    ID_USUARIO INT(6) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL, 
    CORREO VARCHAR(50) NOT NULL, 
    CONTRASENA VARCHAR(25) NOT NULL, 
    ID_ROL INT(2) NOT NULL, 
    ESTATUS INT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_USUARIO),
    FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT(6) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL, 
    CANTIDAD INT(8) NOT NULL DEFAULT 0,
    ESTATUS INT(1) DEFAULT 1,
    PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE HISTORIAL (
    ID_HISTORIAL INT(6) AUTO_INCREMENT NOT NULL,
    ID_USUARIO INT(6) NOT NULL,
    ID_PRODUCTO INT(6) NOT NULL,
    MOVIMIENTO INT(1) NOT NULL, 
    CANTIDAD INT(8) NOT NULL,
    FECHA DATE NOT NULL, 
    HORA TIME NOT NULL, 
    PRIMARY KEY (ID_HISTORIAL),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);

DELIMITER $$
CREATE PROCEDURE SP_HISTORIAL()
BEGIN
	SELECT 
		H.ID_PRODUCTO,
		U.NOMBRE AS USUARIO,
        P.NOMBRE AS PRODUCTO,
        H.MOVIMIENTO,
        H.CANTIDAD,
        H.FECHA,
        H.HORA
	FROM HISTORIAL AS H 
    JOIN USUARIOS AS U ON H.ID_USUARIO = U.ID_USUARIO
    JOIN PRODUCTOS AS P ON H.ID_PRODUCTO = P.ID_PRODUCTO;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE SP_HISTORIAL_ESTATUS(IN H_ESTATUS INT)
BEGIN
	SELECT 
		H.ID_PRODUCTO,
		U.NOMBRE AS USUARIO,
        P.NOMBRE AS PRODUCTO,
        H.MOVIMIENTO,
        H.CANTIDAD,
        H.FECHA,
        H.HORA
	FROM HISTORIAL AS H 
    JOIN USUARIOS AS U ON H.ID_USUARIO = U.ID_USUARIO
    JOIN PRODUCTOS AS P ON H.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE P.ESTATUS = H_ESTATUS
    ORDER BY H.ID_HISTORIAL;
END$$
DELIMITER ;